name: Generate and Publish Site-Tree

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install wget and tree
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y wget tree

      - name: Mirror live site
        run: |
          rm -rf site-mirror
          wget --mirror --quiet --convert-links --no-parent \
               https://cameronbrooks11.github.io \
               -P site-mirror

      - name: Generate markdown tree snippet
        run: |
          ROOT="site-mirror/cameronbrooks11.github.io"
          tree -fi --noreport -L 3 "$ROOT" | \
            sed "s|$ROOT||" | \
            sed '/^$/d' | \
            awk '{
              path=$0
              sub(/\/$/,"",path)
              if (path ~ /index\.html$/) {
                link = substr(path, 1, length(path)-10)
                text = (link==""?"/":link)
              } else {
                link = path
                text = path
              }
              if (link !~ /^\//) link = "/" link
              print "- [" text "](" link ")"
            }' > SITE_TREE_SNIPPET.md

          {
            echo ""
            echo "## Site Tree"
            cat SITE_TREE_SNIPPET.md
          } >> index.markdown

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update site tree"
          branch: "auto/site-tree-${{ github.run_number }}"
          title: "chore: auto-update site tree"
          body: |
            This PR was automatically generated by the site-tree workflow.
