# File: .github/workflows/site-tree.yml
name: Generate and Publish Site-Tree

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install wget and tree
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y wget tree

      - name: Mirror live site
        run: |
          rm -rf site-mirror
          wget --mirror --no-parent \
               https://cameronbrooks11.github.io \
               -P site-mirror || true

      - name: Generate markdown tree snippet
        run: |
          set -euo pipefail

          ROOT="site-mirror/cameronbrooks11.github.io"

          # 1) Build raw tree
          tree -fi --noreport -L 3 "$ROOT" | \
            sed "s|$ROOT||" | sed '/^$/d' | \
            awk '{
              path=$0; sub(/\/$/,"",path)
              if (path ~ /index\.html$/) {
                link = substr(path,1,length(path)-11)
                link = (link==""?"/":link)
              } else link = path
              if (link !~ /^\//) link="/" link
              print "- [" link "](" link ")"
            }' > SITE_TREE_RAW.md

          # 2) Clean ignore file
          sed 's/#.*//' .site-tree-ignore | sed '/^[[:space:]]*$/d' > IGNORE_CLEAN

          # 3) Filter & de-dup
          grep -v -E -f IGNORE_CLEAN SITE_TREE_RAW.md \
            | awk '!seen[$0]++' \
            > SITE_TREE_FILTERED.md

          # 4) Remove existing Site Tree section
          sed -i '/^## Site Tree/,$d' index.markdown

          # 5) Append fresh Site Tree
          {
            echo ""
            echo "## Site Tree"
            cat SITE_TREE_FILTERED.md
          } >> index.markdown

      - name: Clean up temp files
        run: |
          rm -rf site-mirror SITE_TREE_RAW.md IGNORE_CLEAN SITE_TREE_FILTERED.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update site tree"
          branch: "auto/site-tree-${{ github.run_number }}"
          title: "chore: update site tree"
          body: |
            This PR was automatically generated by the site-tree workflow.
          add-paths: |
            index.markdown
